# Generated by Django 3.2.12 on 2022-04-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=256, unique=True)),
                ('email', models.CharField(max_length=256)),
                ('date_birthday', models.DateField(null=True)),
                ('is_email_confirm', models.BooleanField(default=False)),
                ('email_confirm_code', models.CharField(max_length=6)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
