# Generated by Django 3.2.12 on 2022-05-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
